### ISSUE TITLE
Support KSP 1.10 comets in "extras" configs

### ISSUE THREAD

**Issue by Starstrider42** [Starstrider42/Custom-Asteroids-Extras#2]
Once Starstrider42/Custom-Asteroids#47 is implemented, create versions of the configs that use stock comets. Depending on how the parent issue is resolved, these configs will likely require KSP 1.10 or later.

**Comment by HSJasperism** [comment]
> 
> 
> Once [Starstrider42/Custom-Asteroids#47](https://github.com/Starstrider42/Custom-Asteroids/issues/47) is implemented, create versions of the configs that use stock comets. Depending on how the parent issue is resolved, these configs will likely require KSP 1.10 or later.

I'll try to update these as soon as the main mod is compatible with with 1.10 comets (do you need anything particular for the main mod?)

Meanwhile, I can start getting statistics on distribution and prepare a good game-ified version for OPM.

**Comment by HSJasperism** [comment]
Hey. Kopernicus is still locked to 1.8, with some unofficial 1.9 compiles making the rounds. If this is updated for 1.10, it still needs to wait for Kopernicus before testing can be done.

**Comment by Starstrider42** [comment]
Sorry, but Starstrider42/Custom-Asteroids#47 really is a blocker for this. The more comet-like aspects of 1.10 comets (including tails) aren't done by `PartModule`s like they are for asteroids, so there will need to be some code changes before CA comets will work like players expect.

I assume the same holds for Kopernicus, so it may be a while before this issue is doable.

**Comment by Starstrider42** [comment]
I've tested the new configs on KSP 1.11 with OPM 2.2.8 and Kopernicus R-T-B 61.

The biggest change is that, since for the stock game intermediate-period comets are now defined in `Stockalike.cfg` instead of `Trans-Jool.cfg`, `Trans-Neidon.cfg` rescales those instead of rolling its own. I don't think the soft dependency will be a problem in practice, but I plan to have CKAN recommend Stockalike to Trans-Neidon users just in case.
